# Generated by Django 4.0 on 2022-09-02 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 2, 19, 29, 44, 856331)),
        ),
    ]
