# Generated by Django 4.0 on 2022-09-02 14:07

import autoslug.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvt', '0003_alter_posts_publish_alter_posts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 2, 19, 37, 48, 249888)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, max_length=250, null=True, populate_from='title', unique=True),
        ),
    ]
