# Generated by Django 4.0 on 2022-09-03 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvt', '0005_alter_posts_publish_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 3, 13, 56, 36, 375570)),
        ),
    ]
